develop-core
venkatesh9959/React-practice pull request #5
Opened 2022-04-19 11:30 UTC by venkatesh9959

2022-04-20 05:18 UTC, ims7inc requested changes

2022-04-20 05:18 UTC, ims7inc commented on src/Components/Button.tsx
> +  onClickHandler?: any;
why this type is any?

2022-04-20 05:18 UTC, ims7inc commented on src/Components/Button.tsx
>    const { type, value, ButtonText, onClickHandler, disable, addclass } = props;
ButtonText to buttonText

2022-04-20 05:18 UTC, ims7inc commented on src/Pages/Login.tsx
> +    const [open, setOpen] = React.useState(false);
why did you used React.useState here? you can use useState

2022-04-20 05:18 UTC, ims7inc commented on src/Pages/Login.tsx
> +        if (Email == undefined && Password == undefined) {
check for undefined & "" as well **if (!Email && !Password)**

2022-04-20 05:18 UTC, ims7inc commented on src/Pages/Login.tsx
> +    const handleToggle = () => {
toggle for what? give meaning full name

2022-04-20 05:18 UTC, ims7inc commented on src/Pages/Login.tsx
> +    const handleClose = () => {
close for what?

2022-04-20 05:18 UTC, ims7inc commented on src/Pages/Login.tsx
> +    const onchageLogin = (key: string, value: string) => {
onLoginChange

2022-05-05 08:51 UTC, ims7inc requested changes

2022-05-05 08:51 UTC, ims7inc commented on src/Pages/Login/Login.tsx
> +      return true;
why return statement here?

2022-05-05 08:51 UTC, ims7inc commented on src/Pages/Login/Login.tsx
> +      return false;
why return?

2022-05-05 08:51 UTC, ims7inc commented on src/Pages/Login/Login.tsx
> +                                type="checkbox"
on remember me what is th functionality ?

2022-05-05 09:29 UTC, venkatesh9959 commented on src/Pages/Login/Login.tsx
> +      return true;
Line :37 condtion false  ayithe return false ....
retutn rayaothe page next page veluthundi
Line:54 conditin is true ayithe return true

2023-07-07 06:52 UTC, closed without merging